### ISSUE TITLE
Unsound `From<&mut str>` for `&mut StringBase<[u8]>`

### ISSUE THREAD

**Issue by shinmao** [conradludgate/generic-str#1]
https://github.com/conradludgate/generic-str/blob/7d877b6063ab5acd1033672c20d276f26b53112f/src/traits_utf8.rs#L107-L111
The `From` implementation above provided a way to transmute from `&mut str` to `&mut StringBase<[u8]>`. However, this two mutable reference will still point to the same memory address. It means that if we change the `u8` byte slice value to invalid UTF-8, then it could produce invalid `str` at the same time.

The root cause here is that the `u8` byte slice is mutable.

Please let me know if I am wrong;)

**Comment by conradludgate** [comment]
StringBase<[u8]> also requires UTF8 representation, so the underlying str does not have its rules violated

**Comment by shinmao** [comment]
Gotcha. Now I understand that String32 is derived from StringBase and both requires UTF-8 representation. I will close the issue!
